name: 'Build Animate'

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Cancel jobs running if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Build Animate'
    runs-on: ubuntu-latest
    container:
      image: jwallwork/firedrake-parmmg:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2

      - name: 'Cleanup'
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build

      - name: 'Setup python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 'Lint'
        if: ${{ always() }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          flake8 --ignore=E501,E226,E402,E741,F403,F405,W503

      - name: 'Test Animate'
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          python -m pytest -v -n auto test/test_math.py

  docker:
    name: 'Build Docker container'
    if: ${{ (github.ref == 'refs/heads/main') && always() }}
    needs: [build]
    uses: ./.github/workflows/docker.yml
    with:
      status: ${{ needs.build.result }}
    secrets: inherit
